export const palette = {
  brown950: '#1A1209',
  brown900: '#2C1810',
  brown800: '#4A2C1A',
  brown700: '#6B3E26',
  brown600: '#7C4A2D',
  brown500: '#8B5E3C',
  brown400: '#A67C52',
  brown300: '#C4A77D',
  brown200: '#E8DDD0',
  brown100: '#F5EDE4',
  cream: '#FAF7F2',
  gold: '#C9A66B',
  goldLight: '#E8D4A8',
  white: '#FFFFFF',
  black: '#0D0A08',
  success: '#3D8B5F',
  error: '#C45C4A',
  overlay: 'rgba(44, 24, 16, 0.55)',
};

export const lightTheme = {
  mode: 'light' as const,
  colors: {
    primary: palette.brown600,
    primaryDark: palette.brown800,
    primaryLight: palette.brown400,
    accent: palette.gold,
    background: palette.cream,
    surface: palette.white,
    surfaceElevated: palette.white,
    card: palette.white,
    text: palette.brown900,
    textSecondary: palette.brown500,
    textMuted: palette.brown400,
    textOnPrimary: palette.cream,
    border: palette.brown200,
    tabBar: palette.white,
    tabBarActive: palette.brown600,
    tabBarInactive: palette.brown300,
    gradientStart: palette.brown800,
    gradientEnd: palette.brown600,
    shadow: palette.brown900,
    error: palette.error,
    success: palette.success,
    brown200: palette.brown200,
    white: palette.white,
  },
};

export const darkTheme = {
  mode: 'dark' as const,
  colors: {
    primary: palette.brown400,
    primaryDark: palette.brown700,
    primaryLight: palette.brown300,
    accent: palette.gold,
    background: palette.brown950,
    surface: palette.brown900,
    surfaceElevated: palette.brown800,
    card: palette.brown800,
    text: palette.cream,
    textSecondary: palette.brown200,
    textMuted: palette.brown400,
    textOnPrimary: palette.cream,
    border: palette.brown700,
    tabBar: palette.brown900,
    tabBarActive: palette.gold,
    tabBarInactive: palette.brown400,
    gradientStart: palette.brown950,
    gradientEnd: palette.brown700,
    shadow: palette.black,
    error: palette.error,
    success: palette.success,
    brown200: palette.brown300,
    white: palette.white,
  },
};

export type Theme = typeof lightTheme | typeof darkTheme;
